package com.unitTestGenerator.util.random.servicesRandom;


public interface IAddressRandomService {


    //https://www.britannica.com/topic/list-of-cities-and-towns-in-the-United-States-2023068#ref326635

    public static final String[] states = {"Alabama","Alaska","Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky"};

    public static final String[] Alabama = {"Alexander City","Andalusia","Anniston","Athens","Atmore","Auburn","Bessemer","Birmingham","Chickasaw","Clanton","Cullman","Decatur","Demopolis","Dothan","Enterprise","Eufaula","Florence","Fort Payne","Gadsden","Greenville","Guntersville","Huntsville","Jasper","Marion","Mobile","Montgomery","Opelika","Ozark","Phenix City","Prichard","Scottsboro","Selma","Sheffield","Sylacauga","Talladega","Troy","Tuscaloosa","Tuscumbia","Tuskegee"};

    public static final String[] Alaska = {"Anchorage","Cordova","Fairbanks","Haines","Homer","Juneau","Ketchikan","Kodiak","Kotzebue","Nome","Palmer","Seward","Sitka","Skagway","Valdez"};

    public static final String[] Arizona ={"Lake Havasu City","Ajo","Avondale","Bisbee","Casa Grande","Chandler","Clifton","Douglas","Flagstaff","Florence","Gila Bend","Glendale","Globe","Kingman","Mesa","Nogales","Oraibi","Phoenix","Prescott","Scottsdale","Sierra Vista","Tempe","Tombstone","Tucson","Walpi","Window Rock","Winslow","Yuma"};

    public static final String[] Arkansas ={"North Little Rock","Arkansas Post","Arkadelphia","Batesville","Benton","Blytheville","Camden","Conway","Crossett","El Dorado","Fayetteville","Forrest City","Fort Smith","Harrison","Helena","Hope","Hot Springs","Jacksonville","Jonesboro","Little Rock","Magnolia","Morrilton","Newport","Osceola","Pine Bluff","Rogers","Searcy","Stuttgart","Van Buren","West Memphis"};

    public static final String[] California = {"San Juan Capistrano","Alameda","Alhambra","Anaheim","Antioch","Arcadia","Bakersfield","Barstow","Belmont","Berkeley","Beverly Hills","Brea","Buena Park","Burbank","Calexico","Calistoga","Carlsbad","Carmel","Chico","Chula Vista","Claremont","Compton","Concord","Corona","Coronado","Costa Mesa","Culver City","Daly City","Davis","Downey","El Centro","El Cerrito","El Monte","Escondido","Eureka","Fairfield","Fontana","Fremont","Fresno","Fullerton","Garden Grove","Glendale","Hayward","Hollywood","Huntington Beach","Indio","Inglewood","Irvine","La Habra","Laguna Beach","Lancaster","Livermore","Lodi","Lompoc","Long Beach","Los Angeles","Malibu","Martinez","Marysville","Menlo Park","Merced","Modesto","Monterey","Mountain View","Napa","Needles","Newport Beach","Norwalk","Novato","Oakland","Oceanside","Ojai","Ontario","Orange","Oroville","Oxnard","Pacific Grove","Palm Springs","Palmdale","Palo Alto","Pasadena","Petaluma","Pomona","Port Hueneme","Rancho Cucamonga","Red Bluff","Redding","Redlands","Redondo Beach","Redwood City","Richmond","Riverside","Roseville","Sacramento","Salinas","San Bernardino","San Clemente","San Diego","San Fernando","San Francisco","San Gabriel","San Jose","San Leandro","San Luis Obispo","San Marino","San Mateo","San Pedro","San Rafael","San Simeon","Santa Ana","Santa Barbara","Santa Clara","Santa Clarita","Santa Cruz","Santa Monica","Santa Rosa","Sausalito","Simi Valley","Sonoma","South San Francisco","Stockton","Sunnyvale","Susanville","Thousand Oaks","Torrance","Turlock","Ukiah","Vallejo","Ventura","Victorville","Visalia","Walnut Creek","Watts","West Covina","Whittier","Woodland","Yorba Linda","Yuba City"};

    public static final String[] Colorado = {"Steamboat Springs","Alamosa","Aspen","Aurora","Boulder","Breckenridge","Brighton","Canon City","Central City","Climax","Colorado Springs","Cortez","Cripple Creek","Denver","Durango","Englewood","Estes Park","Fort Collins","Fort Morgan","Georgetown","Glenwood Springs","Golden","Grand Junction","Greeley","Gunnison","La Junta","Leadville","Littleton","Longmont","Loveland","Montrose","Ouray","Pagosa Springs","Pueblo","Silverton","Sterling","Telluride","Trinidad","Vail","Walsenburg","Westminster"};

    public static final String[] Connecticut ={"East Hartford","Old Saybrook ", "Ansonia","Berlin","Bloomfield","Branford","Bridgeport","Bristol","Coventry","Danbury","Darien","Derby","East Haven","Enfield","Fairfield","Farmington","Greenwich","Groton","Guilford","Hamden","Hartford","Lebanon","Litchfield","Manchester","Mansfield","Meriden","Middletown","Milford","Mystic","Naugatuck","New Britain","New Haven","New London","North Haven","Norwalk","Norwich","Orange","Seymour","Shelton","Simsbury","Southington","Stamford","Stonington","Stratford","Torrington","Wallingford","Waterbury","Waterford","Watertown","West Hartford","West Haven","Westport","Wethersfield","Willimantic","Windham","Windsor","Windsor Locks","Winsted"};

    public static final String[] Delaware = {"Wilmington","New Castle","Dover","Lewes","Milford","Newark","Smyrna"};

    public static final String[] Florida = {"Saint Petersburg","Bartow","Belle Glade","Boca Raton","Bradenton","Cape Coral","Clearwater","Cocoa Beach","Cocoa-Rockledge","Coral Gables","Daytona Beach","De Land","Deerfield Beach","Delray Beach","Fernandina Beach","Fort Lauderdale","Fort Myers","Fort Pierce","Fort Walton Beach","Gainesville","Hallandale Beach","Hialeah","Hollywood","Homestead","Jacksonville","Key West","Lake City","Lake Wales","Lakeland","Largo","Melbourne","Miami","Miami Beach","Naples","New Smyrna Beach","Ocala","Orlando","Ormond Beach","Palatka","Palm Bay","Palm Beach","Panama City","Pensacola","Pompano Beach","Saint Augustine","Sanford","Sarasota","Sebring","Tallahassee","Tampa","Tarpon Springs","Titusville","Venice","West Palm Beach","White Springs","Winter Haven","Winter Park"};

    public static final String[] Georgia = {"Warner Robins","Albany","Americus","Andersonville","Athens","Atlanta","Augusta","Bainbridge","Blairsville","Brunswick","Calhoun","Carrollton","Columbus","Dahlonega","Dalton","Darien","Decatur","Douglas","East Point","Fitzgerald","Fort Valley","Gainesville","La Grange","Macon","Marietta","Milledgeville","Plains","Rome","Savannah","Toccoa","Valdosta","Warm Springs","Washington","Waycross",};

    public static final String[] Hawaii = {"Honaunau","Hanalei","Hilo","Honolulu","Kahului","Kaneohe","Kapaa","Kawaihae","Lahaina","Laie","Wahiawa","Wailuku","Waimea"};

    public static final String[] Idaho = {"Coeur d’Alene","Blackfoot","Boise","Bonners Ferry","Caldwell","Idaho City","Idaho Falls","Kellogg","Lewiston","Moscow","Nampa","Pocatello","Priest River","Rexburg","Sun Valley","Twin Falls"};

    public static final String[] Illinois = {"Arlington Heights","East Saint Louis","Alton","Arthur","Aurora","Belleville","Belvidere","Bloomington","Brookfield","Cahokia","Cairo","Calumet City","Canton","Carbondale","Carlinville","Carthage","Centralia","Champaign","Charleston","Chester","Chicago","Chicago Heights","Cicero","Collinsville","Danville","Decatur","DeKalb","Des Plaines","Dixon","East Moline","South Holland","Effingham","Elgin","Elmhurst","Evanston","Freeport","Galena","Galesburg","Glen Ellyn","Glenview","Granite City","Harrisburg","Herrin","Highland Park","Jacksonville","Joliet","Kankakee","Kaskaskia","Kewanee","La Salle","Lake Forest","Libertyville","Lincoln","Lisle","Lombard","Macomb","Mattoon","Moline","Monmouth","Mount Vernon","Mundelein","Naperville","Nauvoo","Normal","North Chicago","Oak Park","Oregon","Ottawa","Palatine","Park Forest","Park Ridge","Pekin","Peoria","Petersburg","Pontiac","Quincy","Rantoul","River Forest","Rock Island","Rockford","Salem","Shawneetown","Skokie","Springfield","Streator","Summit","Urbana","Vandalia","Virden","Waukegan","Wheaton","Wilmette","Winnetka","Wood River","Zion"};

    public static final String[] Indiana = {"Jeffersonville", "Anderson", "Bedford", "Bloomington", "Columbus", "Connersville", "Corydon", "Crawfordsville", "East Chicago", "Elkhart", "Elwood", "Evansville", "Fort Wayne", "French Lick", "Gary", "Geneva", "Goshen", "Greenfield", "Hammond", "Hobart", "Huntington", "Indianapolis", "Kokomo", "Lafayette", "Madison", "Marion", "Michigan City", "Mishawaka", "Muncie", "Nappanee", "Nashville", "New Albany", "New Castle", "New Harmony", "Peru", "Plymouth", "Richmond", "Santa Claus", "Shelbyville", "South Bend", "Terre Haute", "Valparaiso", "Vincennes", "Wabash", "West Lafayette"};

    public static final String[] Iowa = {"West Des Moines","Amana Colonies","Ames","Boone","Burlington","Cedar Falls","Cedar Rapids","Charles City","Cherokee","Clinton","Council Bluffs","Davenport","Des Moines","Dubuque","Estherville","Fairfield","Fort Dodge","Grinnell","Indianola","Iowa City","Keokuk","Mason City","Mount Pleasant","Muscatine","Newton","Oskaloosa","Ottumwa","Sioux City","Waterloo","Webster City"};

    public static final String[] Kansas ={"Medicine Lodge","Abilene","Arkansas City","Atchison","Chanute","Coffeyville","Council Grove","Dodge City","Emporia","Fort Scott","Garden City","Great Bend","Hays","Hutchinson","Independence","Junction City","Kansas City","Lawrence","Leavenworth","Liberal","Manhattan","McPherson","Newton","Olathe","Osawatomie","Ottawa","Overland Park","Pittsburg","Salina","Shawnee","Smith Center","Topeka","Wichita"};

    public static final String[] Kentucky={"Campbellsville","Ashland","Barbourville","Bardstown","Berea","Boonesborough","Bowling Green","Covington","Danville","Elizabethtown","Frankfort","Harlan","Harrodsburg","Hazard","Henderson","Hodgenville","Hopkinsville","Lexington","Louisville","Mayfield","Maysville","Middlesboro","Newport","Owensboro","Paducah","Paris","Richmond"};

    public static final String[] streetNames = {"Main Street","2nd Street","3rd Street","4th Street","5th Street","6th Street","7th Street","1st Street","8th Street","9th Street", "Park Avenue", "Elm Street", "Sunset Boulevard", "Broadway","Weston Manor Drive Sumter ","Queensbury Terrace Sumter ","Westover Way Sumter ","Westwind Way Sumter ","Wettstein Way VOWL ","Whalin Way VOSO ","Wheeling Way Sumter ","Wheelock Street Sumter ","Whisper Street","Tambourine Terrace Sumter ","Tammy Lane VOWL ","Tampico Place Sumter ","Tangelo Lane Sumter ","Tangerine Circle Lake ","Tangerine Drive Lake ","Tanglewood Place Sumter ","Tango Street Sumter","Tannery Terrace Sumter ","Tanya Terrace VOWL ","Taos Way ","Sanford Street VOSO ","Sanibel Court Sumter ","Sansores Street Sumter ","Santa Anna Lane Sumter ","Santa Barbara Blvd. ","Santa Clara Circle Sumter ","Santa Cruz Drive Sumter ","Santa Fe Street Sumter ","Santa Maria Avenue Sumter ","Santa Rita Way Lake ","Santa Rosa Court Sumter ","Santana Way","Quary Place Sumter ","Quasar Avenue Sumter ","Queen Palm Place Sumter ","Queensway Terrace Sumter ","Quelly Road VOSO","Quiet Oak Court Sumter ","Quietwoods Drive Sumter ","Quill Avenue Sumter ","Quinby Way Sumter ","Quincy Court Sumter ","Quinn Lane Sumter ","Quintero Court Sumter ","Rabbit Run Path Sumter ","Raccoon Road"};

    public static final String[] AlabamaCounty ={"Covington County","Cleburne County","Autauga County","Baldwin County","Barbour County","Bibb County","Blount County","Bullock County","Butler County","Calhoun County","Chambers County","Cherokee County","Chilton County","Choctaw County","Clarke County","Clay County","Coffee County","Colbert County","Conecuh County","Coosa County","Crenshaw County","Cullman County","Dale County","Dallas County","DeKalb County","Elmore County","Escambia County","Etowah County","Fayette County","Franklin County","Geneva County","Greene County","Hale County","Henry County","Houston County","Jackson County","Jefferson County","Lamar County","Lauderdale County","Lawrence County","Lee County","Limestone County","Lowndes County","Macon County","Madison County","Marengo County","Marion County","Marshall County","Mobile County","Monroe County","Montgomery County","Morgan County","Perry County","Pickens County","Pike County","Randolph County","Russell County","Saint Clair County","Shelby County","Sumter County","Talladega County","Tallapoosa County","Tuscaloosa County","Walker County","Washington County","Wilcox County","Winston County"};

    public static final String[] AlaskaCounty ={"Fairbanks North Star Borough","Aleutians East Borough","Anchorage Borough","Bristol Bay Borough","Denali Borough","Haines Borough","Juneau Borough","Kenai Peninsula Borough","Ketchikan Gateway Borough","Kodiak Island Borough","Lake and Peninsula Borough","Matanuska-Susitna Borough","North Slope Borough","Northwest Arctic Borough","Petersburg Borough","Sitka Borough","Skagway Borough","Wrangell Borough","Yakutat Borough"};

    public static final String[] ArizonaCounty ={"Santa Cruz County","County Job Board","Apache County","Cochise County","Coconino County","Gila County","Graham County","Greenlee County","La Paz County","Maricopa County","Mohave County","Navajo County","Pima County","Pinal County","Yavapai County","Yuma County"};

    public static final String[] ArkansasCounty ={"Saint Francis","Arkansas","Ashley","Baxter","Benton","Boone","Bradley","Calhoun","Carroll","Chicot","Clark","Clay","Cleburne","Cleveland","Columbia","Conway","Craighead","Crawford","Crittenden","Cross","Dallas","Desha","Drew","Faulkner","Franklin","Fulton","Garland","Grant","Greene","Hempstead","Hot Spring","Howard","Independence","Izard","Jackson","Jefferson","Johnson","Lafayette","Lawrence","Lee","Lincoln","Little River","Logan","Lonoke","Madison","Marion","Miller","Mississippi","Monroe","Montgomery","Nevada","Newton","Ouachita","Perry","Phillips","Pike","Poinsett","Polk","Pope","Prairie","Pulaski","Randolph","Saline","Scott","Searcy","Sebastian","Sevier","Sharp","Stone","Union","Van Buren","Washington","White","Woodruff","Yell"};

    public static final String[] CaliforniaCounty ={"San Luis Obispo","Contra Costa","Alameda","Alpine","Amador","Butte","Calaveras","Colusa","Del Norte","El Dorado","Fresno","Glenn","Humboldt","Imperial","Inyo","Kern","Kings","Lake","Lassen","Los Angeles","Madera","Marin","Mariposa","Mendocino","Merced","Modoc","Mono","Monterey","Napa","Nevada","Orange","Placer","Plumas","Riverside","Sacramento","San Benito","San Bernardino","San Diego","San Francisco","San Joaquin","San Mateo","Santa Barbara","Santa Clara","Santa Cruz","Shasta","Sierra","Siskiyou","Solano","Sonoma","Stanislaus","Sutter","Tehama","Trinity","Tulare","Tuolumne","Ventura","Yolo","Yuba"};

    public static final String[] ColoradoCounty ={"Clear Creek ","Adams ","Alamosa ","Arapahoe ","Archuleta ","Baca ","Bent ","Boulder ","Broomfield ","Chaffee ","Cheyenne ","Conejos ","Costilla ","Crowley ","Custer ","Delta ","Denver ","Dolores ","Douglas ","Eagle ","El Paso ","Elbert ","Fremont ","Garfield ","Gilpin ","Grand ","Gunnison ","Hinsdale ","Huerfano ","Jackson ","Jefferson ","Kiowa ","Kit Carson ","La Plata ","Lake ","Larimer ","Las Animas ","Lincoln ","Logan ","Mesa ","Mineral ","Moffat ","Montezuma ","Montrose ","Morgan ","Otero ","Ouray ","Park ","Phillips ","Pitkin ","Prowers ","Pueblo ","Rio Blanco ","Rio Grande ","Routt ","Saguache ","San Juan ","San Miguel ","Sedgwick ","Summit ","Teller ","Washington ","Weld ","Yuma"};

    public static final String[]  ConnecticutCounty ={"Litchfield","New London","Fairfield","Hartford","Middlesex","New Haven","Tolland","Windham"};

    public static final String[]  DelawareCounty ={"Glen Riddle Lima","Aston","Brookhaven","Broomall","Bryn Mawr","Chadds Ford","Chester","Chester Heights","Cheyney","Clifton Heights","Concordville","Crum Lynne","Darby","Drexel Hill","Edgemont","Essington","Folcroft","Folsom","Garnet Valley","Glen Mills","Glenolden","Havertown","Holmes","Lansdowne","Lenni","Marcus Hook","Media","Morton","Newtown Square","Norwood","Philadelphia","Prospect Park","Ridley Park","Sharon Hill","Springfield","Swarthmore","Thornton","Upper Darby","Villanova","Wallingford","Wayne","Woodlyn"};

    public static final String[]  FloridaCounty ={"Indian River","Alachua","Baker","Bay","Bradford","Brevard","Broward","Calhoun","Charlotte","Citrus","Clay","Collier","Columbia","DeSoto","Dixie","Duval","Escambia","Flagler","Franklin","Gadsden","Gilchrist","Glades","Gulf","Hamilton","Hardee","Hendry","Hernando","Highlands","Hillsborough","Holmes","Jackson","Jefferson","Lafayette","Lake","Lee","Leon","Levy","Liberty","Madison","Manatee","Marion","Martin","Miami-Dade","Monroe","Nassau","Okaloosa","Okeechobee","Orange","Osceola","Palm Beach","Pasco","Pinellas","Polk","Putnam","Saint Johns","Saint Lucie","Santa Rosa","Sarasota","Seminole","Sumter","Suwannee","Taylor","Union","Volusia","Wakulla","Walton","Washington"};

    public static final String[]  GeorgiaCounty ={"Chattahoochee","Appling","Atkinson","Bacon","Baker","Baldwin","Banks","Barrow","Bartow","Ben Hill","Berrien","Bibb","Bleckley","Brantley","Brooks","Bryan","Bulloch","Burke","Butts","Calhoun","Camden","Candler","Carroll","Catoosa","Charlton","Chatham","Chattooga","Cherokee","Clarke","Clay","Clayton","Clinch","Cobb","Coffee","Colquitt","Columbia","Cook","Coweta","Crawford","Crisp","Dade","Dawson","Decatur","Dekalb","Dodge","Dooly","Dougherty","Douglas","Early","Echols","Effingham","Elbert","Emanuel","Evans","Fannin","Fayette","Floyd","Forsyth","Franklin","Fulton","Gilmer","Glascock","Glynn","Gordon","Grady","Greene","Gwinnett","Habersham","Hall","Hancock","Haralson","Harris","Hart","Heard","Henry","Houston","Irwin","Jackson","Jasper","Jeff Davis","Jefferson","Jenkins","Johnson","Jones","Lamar","Lanier","Laurens","Lee","Liberty","Lincoln","Long","Lowndes","Lumpkin","Macon","Madison","Marion","McDuffie","McIntosh","Meriwether","Miller","Mitchell","Monroe","Montgomery","Morgan","Murray","Muscogee","Newton","Oconee","Oglethorpe","Paulding","Peach","Pickens","Pierce","Pike","Polk","Pulaski","Putnam","Quitman","Rabun","Randolph","Richmond","Rockdale","Schley","Screven","Seminole","Spalding","Stephens","Stewart","Sumter","Talbot","Taliaferro","Tattnall","Taylor","Telfair","Terrell","Thomas","Tift","Toombs","Towns","Treutlen","Troup","Turner","Twiggs","Union","Upson","Walker","Walton","Ware","Warren","Washington","Wayne","Webster","Wheeler","White","Whitfield","Wilcox","Wilkes","Wilkinson","Worth"};

    public static final String[]  HawaiiCounty ={"Hawaii National Park","Captain Cook","Hakalau","Hawi","Hilo","Holualoa","Honaunau","Honokaa","Honomu","Kailua Kona","Kamuela","Kapaau","Keaau","Kealakekua","Keauhou","Kurtistown","Laupahoehoe","Mountain View","Naalehu","Ninole","Ocean View","Ookala","Paauilo","Pahala","Pahoa","Papaaloa","Papaikou","Pepeekeo","Volcano","Waikoloa"};

    public static final String[]  IdahoCounty ={"Clearwater County","Washington County","Ada County","Adams County","Bannock County","Bear Lake County","Benewah County","Bingham County","Blaine County","Boise County","Bonner County","Bonneville County","Boundary County","Butte County","Camas County","Canyon County","Caribou County","Cassia County","Clark County","Custer County","Elmore County","Franklin County","Fremont County","Gem County","Gooding County","Idaho County","Jefferson County","Jerome County","Kootenai County","Latah County","Lemhi County","Lewis County","Lincoln County","Madison County","Minidoka County","Nez Perce County","Oneida County","Owyhee County","Payette County","Power County","Shoshone County","Teton County","Twin Falls County","Valley County"};

    public static final String[]  IllinoisCounty ={"Rock Island","Adams","Alexander","Bond","Boone","Brown","Bureau","Calhoun","Carroll","Cass","Champaign","Christian","Clark","Clay","Clinton","Coles","Cook","Crawford","Cumberland","DeKalb","DeWitt","Douglas","DuPage","Edgar","Edwards","Effingham","Fayette","Ford","Franklin","Fulton","Gallatin","Greene","Grundy","Hamilton","Hancock","Hardin","Henderson","Henry","Iroquois","Jackson","Jasper","Jefferson","Jersey","Jo Daviess","Johnson","Kane","Kankakee","Kendall","Knox","Lake","LaSalle","Lawrence","Lee","Livingston","Logan","Macon","Macoupin","Madison","Marion","Marshall","Mason","Massac","McDonough","McHenry","McLean","Menard","Mercer","Monroe","Montgomery","Morgan","Moultrie","Ogle","Peoria","Perry","Piatt","Pike","Pope","Pulaski","Putnam","Randolph","Richland","Saint Clair","Saline","Sangamon","Schuyler","Scott","Shelby","Stark","Stephenson","Tazewell","Union","Vermilion","Wabash","Warren","Washington","Wayne","White","Whiteside","Will","Williamson","Winnebago","Woodford"};

    public static final String[]  IndianaCounty ={"Vanderburgh","Adams","Allen","Bartholomew","Benton","Blackford","Boone","Brown","Carroll","Cass","Clark","Clay","Clinton","Crawford","Daviess","Dearborn","Decatur","DeKalb","Delaware","Dubois","Elkhart","Fayette","Floyd","Fountain","Franklin","Fulton","Gibson","Grant","Greene","Hamilton","Hancock","Harrison","Hendricks","Henry","Howard","Huntington","Jackson","Jasper","Jay","Jefferson","Jennings","Johnson","Knox","Kosciusko","Lagrange","Lake","LaPorte","Lawrence","Madison","Marion","Marshall","Martin","Miami","Monroe","Montgomery","Morgan","Newton","Noble","Ohio","Orange","Owen","Parke","Perry","Pike","Porter","Posey","Pulaski","Putnam","Randolph","Ripley","Rush","Scott","Shelby","Spencer","St. Joseph","Starke","Steuben","Sullivan","Switzerland","Tippecanoe","Tipton","Union","Vermillion","Vigo","Wabash","Warren","Warrick","Washington","Wayne","Wells","White","Whitley"};

    public static final String[] IowaCounty ={"Pottawattamie","Cerro Gordo","Adair","Adams","Allamakee","Appanoose","Audubon","Benton","Black Hawk","Boone","Bremer","Buchanan","Buena Vista","Butler","Calhoun","Carroll","Cass","Cedar","Cherokee","Chickasaw","Clarke","Clay","Clayton","Clinton","Crawford","Dallas","Davis","Decatur","Delaware","Des Moines","Dickinson","Dubuque","Emmet","Fayette","Floyd","Franklin","Fremont","Greene","Grundy","Guthrie","Hamilton","Hancock","Hardin","Harrison","Henry","Howard","Humboldt","Ida","Iowa","Jackson","Jasper","Jefferson","Johnson","Jones","Keokuk","Kossuth","Lee","Linn","Louisa","Lucas","Lyon","Madison","Mahaska","Marion","Marshall","Mills","Mitchell","Monona","Monroe","Montgomery","Muscatine","O'Brien","Osceola","Page","Palo Alto","Plymouth","Pocahontas","Polk","Poweshiek","Ringgold","Sac","Scott","Shelby","Sioux","Story","Tama","Taylor","Union","Van Buren","Wapello","Warren","Washington","Wayne","Webster","Winnebago","Winneshiek","Woodbury","Worth","Wright"};

    public static final String[] KansasCounty ={"Pottawatomie County","Allen County","Anderson County","Atchison County","Barber County","Barton County","Bourbon County","Brown County","Butler County","Chase County","Chautauqua County","Cherokee County","Cheyenne County","Clark County","Clay County","Cloud County","Coffey County","Comanche County","Cowley County","Crawford County","Decatur County","Dickinson County","Doniphan County","Douglas County","Edwards County","Elk County","Ellis County","Ellsworth County","Finney County","Ford County","Franklin County","Geary County","Gove County","Graham County","Grant County","Gray County","Greeley County","Greenwood County","Hamilton County","Harper County","Harvey County","Haskell County","Hodgeman County","Jackson County","Jefferson County","Jewell County","Johnson County","Kearny County","Kingman County","Kiowa County","Labette County","Lane County","Leavenworth County","Lincoln County","Linn County","Logan County","Lyon County","Marion County","Marshall County","McPherson County","Meade County","Miami County","Mitchell County","Montgomery County","Morris County","Morton County","Nemaha County","Neosho County","Ness County","Norton County","Osage County","Osborne County","Ottawa County","Pawnee County","Phillips County","Pratt County","Rawlins County","Reno County","Republic County","Rice County","Riley County","Rooks County","Rush County","Russell County","Saline County","Scott County","Sedgwick County","Seward County","Shawnee County","Sheridan County","Sherman County","Smith County","Stafford County","Stanton County","Stevens County","Sumner County","Thomas County","Trego County","Wabaunsee County","Wallace County","Washington County","Wichita County","Wilson County","Woodson County","Wyandotte County"};

    public static final String[] KentuckyCounty ={"Breckinridge County","Adair County","Allen County","Anderson County","Ballard County","Barren County","Bath County","Bell County","Boone County","Bourbon County","Boyd County","Boyle County","Bracken County","Breathitt County","Bullitt County","Butler County","Caldwell County","Calloway County","Campbell County","Carlisle County","Carroll County","Carter County","Casey County","Christian County","Clark County","Clay County","Clinton County","Crittenden County","Cumberland County","Daviess County","Edmonson County","Elliott County","Estill County","Fayette County","Fleming County","Floyd County","Franklin County","Fulton County","Gallatin County","Garrard County","Grant County","Graves County","Grayson County","Green County","Greenup County","Hancock County","Hardin County","Harlan County","Harrison County","Hart County","Henderson County","Henry County","Hickman County","Hopkins County","Jackson County","Jefferson County","Jessamine County","Johnson County","Kenton County","Knott County","Knox County","LaRue County","Laurel County","Lawrence County","Lee County","Leslie County","Letcher County","Lewis County","Lincoln County","Livingston County","Logan County","Lyon County","Madison County","Magoffin County","Marion County","Marshall County","Martin County","Mason County","McCracken County","McCreary County","McLean County","Meade County","Menifee County","Mercer County","Metcalfe County","Monroe County","Montgomery County","Morgan County","Muhlenberg County","Nelson County","Nicholas County","Ohio County","Oldham County","Owen County","Owsley County","Pendleton County","Perry County","Pike County","Powell County","Pulaski County","Robertson County","Rockcastle County","Rowan County","Russell County","Scott County","Shelby County","Simpson County","Spencer County","Taylor County","Todd County","Trigg County","Trimble County","Union County","Warren County","Washington County","Wayne County","Webster County","Whitley County","Wolfe County","Woodford County"};

    public static final Integer[] postalCodes = {10001, 90001, 60601, 75001, 33101, 32300, 32309, 32312, 40000};

    public String generateAddress();
    public boolean fillMaps();
    public String generateRandomStates();
}
