#!/usr/bin/env bash

VERSION="1.0.0"
APP_NAME="unit"
INSTALL_DIR="${HOME}/.${APP_NAME}"
JAR_NAME="unit-1.0.0-jar-with-dependencies.jar"

main() {
    case "$1" in
        install)
            install_cli
            ;;
        uninstall)
            uninstall_cli
            ;;
        --version|-v)
            echo "${VERSION}"
            ;;
        --help|-h)
            show_help
            ;;
        *)
            run_application "$@"
            ;;
    esac
}

install_cli() {
    echo "Installing ${APP_NAME}..."
    mkdir -p "${INSTALL_DIR}"
    cp "$(get_script_path)/${JAR_NAME}" "${INSTALL_DIR}"
    ln -sf "$(get_script_path)/unit" "/usr/local/bin/${APP_NAME}"
    chmod +x /usr/local/bin/${APP_NAME}
    echo "Installation complete! Try '${APP_NAME} --help'"
}

uninstall_cli() {
    echo "Removing ${APP_NAME}..."
    sudo rm -f "/usr/local/bin/${APP_NAME}"
    rm -rf "${INSTALL_DIR}"
    echo "Uninstallation complete..."
}


show_help() {
    cat <<EOF
${APP_NAME} v${VERSION}
Usage:
  ${APP_NAME} [command] [options]

Commands:
  install       Install the application
  uninstall     Remove the application
  --version, -v Show version
  --help, -h    Show this help

Application Options:
  [names...]   List of names to greet
EOF
}

run_application() {
    if command -v java &> /dev/null; then
        java -jar "${INSTALL_DIR}/${JAR_NAME}" "$@"
    else
        echo "Java Runtime not found! Please install Java JRE 1.8+"
        exit 1
    fi
}

get_script_path() {
    SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    echo "${SCRIPT_DIR}"
}

main "$@"